export type Language = 'en' | 'ru';

export const translations = {
  en: {
    // UI
    ui: {
        startGame: 'Start Game',
        backToMenu: 'Back to Menu',
        youWin: 'You Win!',
        youLose: 'You Lose!',
        difficulty: 'Difficulty',
        easy: 'Easy',
        normal: 'Normal',
        hard: 'Hard',
        very_hard: 'Very Hard',
        mapType: 'Map Type',
        addResourcesDebug: 'Debug: Add 500 Gold & Wood',
        enemyPopulation: 'Enemy Population',
        enemyWood: 'Enemy Wood',
        enemyGold: 'Enemy Gold',
        queue: 'Activity Queue',
        cancelTrain: 'Click to cancel training {unitType}',
        cancelResearch: 'Click to cancel research',
        inQueue: '{unitType} in queue',
        researching: 'Researching {researchName}',
        popLimitReached: 'Population limit reached!',
        notEnoughResources: 'Not enough resources!',
        maxLevel: 'MAX',
        level: 'Lvl {level}',
        upgradeTo: 'Upgrade {name} to Lvl {level}',
        researchInProgress: 'Research in progress',
        build: 'Build {buildingType}',
        train: 'Train {unitType}',
        cannotCommandEnemy: 'Cannot issue commands to an enemy.',
        cannotCommandAlly: 'Cannot issue commands to an allied unit.',
        noActions: 'No actions available for this object.',
        multipleSelected: 'Multiple Selected ({count})',
        multipleSelectedUnits: 'Units of various types.',
        multipleSelectedMixed: 'Cannot mix player and enemy units.',
        multipleBuildingsSelected: '{count} x {buildingType}',
        commandCenter: 'Command Center',
        commandCenterDesc: 'Select units or buildings to issue orders.',
        buildModeTitle: 'Build: {buildingType}',
        buildCost: 'Cost: {gold} Gold, {wood} Wood',
        buildCanPlace: 'Click on valid terrain to place.',
        buildCannotPlace: 'Cannot place here.',
        cancelBuild: 'Cancel Build',
        upgradeTower: 'Upgrade to Catapult Tower',
        towerUpgraded: 'Tower already upgraded',
        upgradeInProgress: 'Upgrade in progress',
        installCatapult: 'Install Catapult',
        upgraded: '(Upgraded)',
        combinedQueue: 'Combined Queue',
        menu: 'Menu',
        paused: 'Paused',
        resume: 'Resume Game',
        status: {
            GATHERING_RESOURCE: 'Gathering {resource}',
            ATTACKING_TARGET: 'Attacking {target}',
            BUILDING_TARGET: 'Building {target}',
            REPAIRING_TARGET: 'Repairing {target}',
        }
    },
    // Game Objects
    unit: {
      WORKER: 'Worker',
      INFANTRY: 'Infantry',
      ARCHER: 'Archer',
      CAVALRY: 'Cavalry',
      CATAPULT: 'Catapult',
    },
    building: {
      TOWN_HALL: 'Town Hall',
      BARRACKS: 'Barracks',
      HOUSE: 'House',
      DEFENSIVE_TOWER: 'Defensive Tower',
      WAREHOUSE: 'Warehouse',
      RESEARCH_CENTER: 'Research Center',
      MARKET: 'Market',
    },
    resource: {
        TREE: 'Tree',
        GOLD_MINE: 'Gold Mine'
    },
    map: {
        default: 'Default',
        forest: 'Forest',
        gold_rush: 'Gold Rush',
        open_plains: 'Open Plains',
    },
    status: {
        IDLE: 'Idle',
        MOVING: 'Moving',
        GATHERING: 'Gathering',
        RETURNING: 'Returning',
        BUILDING: 'Building',
        ATTACKING: 'Attacking',
        REPAIRING: 'Repairing',
        FLEEING: 'Fleeing',
    },
    stance: {
        AGGRESSIVE: 'Aggressive',
        HOLD_GROUND: 'Hold Ground',
    },
    // Research
    research: {
        name: {
            MELEE_ATTACK: 'Steel Weapons',
            MELEE_DEFENSE: 'Iron Armor',
            RANGED_ATTACK: 'Bodkin Arrows',
            RANGED_DEFENSE: 'Leather Armor',
            SIEGE_ATTACK: 'Engineering',
            BUILDING_ATTACK: 'Burning Pitch',
            BUILDING_DEFENSE: 'Masonry',
            WORKER_CAPACITY: 'Wheelbarrow',
        },
    }
  },
  ru: {
    // UI
    ui: {
        startGame: 'Начать игру',
        backToMenu: 'В меню',
        youWin: 'Вы победили!',
        youLose: 'Вы проиграли!',
        difficulty: 'Сложность',
        easy: 'Легко',
        normal: 'Нормально',
        hard: 'Сложно',
        very_hard: 'Очень сложно',
        mapType: 'Тип карты',
        addResourcesDebug: 'Отладка: +500 золота и дерева',
        enemyPopulation: 'Население врага',
        enemyWood: 'Дерево врага',
        enemyGold: 'Золото врага',
        queue: 'Очередь',
        cancelTrain: 'Нажмите, чтобы отменить тренировку: {unitType}',
        cancelResearch: 'Нажмите, чтобы отменить исследование',
        inQueue: '{unitType} в очереди',
        researching: 'Исследуется: {researchName}',
        popLimitReached: 'Достигнут лимит населения!',
        notEnoughResources: 'Недостаточно ресурсов!',
        maxLevel: 'МАКС',
        level: 'Ур. {level}',
        upgradeTo: 'Улучшить {name} до Ур. {level}',
        researchInProgress: 'Идет исследование',
        build: 'Строить: {buildingType}',
        train: 'Тренировать: {unitType}',
        cannotCommandEnemy: 'Нельзя отдавать приказы врагу.',
        cannotCommandAlly: 'Нельзя отдавать приказы союзнику.',
        noActions: 'Нет доступных действий.',
        multipleSelected: 'Выбрано несколько ({count})',
        multipleSelectedUnits: 'Юниты разных типов.',
        multipleSelectedMixed: 'Нельзя смешивать своих и вражеских юнитов.',
        multipleBuildingsSelected: 'Выбрано {buildingType}: {count}',
        commandCenter: 'Командный центр',
        commandCenterDesc: 'Выберите юнитов или здания для отдачи приказов.',
        buildModeTitle: 'Строить: {buildingType}',
        buildCost: 'Стоимость: {gold} золота, {wood} дерева',
        buildCanPlace: 'Нажмите на доступную территорию для постройки.',
        buildCannotPlace: 'Здесь строить нельзя.',
        cancelBuild: 'Отменить строительство',
        upgradeTower: 'Улучшить до Башни с катапультой',
        towerUpgraded: 'Башня уже улучшена',
        upgradeInProgress: 'Идет улучшение',
        installCatapult: 'Установить катапульту',
        upgraded: '(Улучшено)',
        combinedQueue: 'Общая очередь',
        menu: 'Меню',
        paused: 'Пауза',
        resume: 'Продолжить игру',
        status: {
            GATHERING_RESOURCE: 'Сбор: {resource}',
            ATTACKING_TARGET: 'Атака: {target}',
            BUILDING_TARGET: 'Строительство: {target}',
            REPAIRING_TARGET: 'Починка: {target}',
        }
    },
    // Game Objects
    unit: {
      WORKER: 'Рабочий',
      INFANTRY: 'Пехотинец',
      ARCHER: 'Лучник',
      CAVALRY: 'Кавалерия',
      CATAPULT: 'Катапульта',
    },
    building: {
      TOWN_HALL: 'Ратуша',
      BARRACKS: 'Казармы',
      HOUSE: 'Дом',
      DEFENSIVE_TOWER: 'Защитная башня',
      WAREHOUSE: 'Склад',
      RESEARCH_CENTER: 'Центр исследований',
      MARKET: 'Рынок',
    },
    resource: {
        TREE: 'Дерево',
        GOLD_MINE: 'Золотая шахта'
    },
    map: {
        default: 'Стандартная',
        forest: 'Лес',
        gold_rush: 'Золотая лихорадка',
        open_plains: 'Равнины',
    },
    status: {
        IDLE: 'Бездействует',
        MOVING: 'Движется',
        GATHERING: 'Собирает',
        RETURNING: 'Возвращается',
        BUILDING: 'Строит',
        ATTACKING: 'Атакует',
        REPAIRING: 'Чинит',
        FLEEING: 'Отступает',
    },
    stance: {
        AGGRESSIVE: 'Агрессивный',
        HOLD_GROUND: 'Держать позицию',
    },
    // Research
    research: {
        name: {
            MELEE_ATTACK: 'Стальное оружие',
            MELEE_DEFENSE: 'Железная броня',
            RANGED_ATTACK: 'Бронебойные стрелы',
            RANGED_DEFENSE: 'Кожаная броня',
            SIEGE_ATTACK: 'Инженерия',
            BUILDING_ATTACK: 'Горючая смола',
            BUILDING_DEFENSE: 'Каменная кладка',
            WORKER_CAPACITY: 'Тачка',
        },
    }
  },
};